# Server Port Configuration
server.port=${PORT:5000}

# Database Configuration
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:h2:file:./data/portfolio_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.driverClassName=${JDBC_DATABASE_DRIVER:org.h2.Driver}
spring.datasource.username=${JDBC_DATABASE_USERNAME:sa}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:}
spring.jpa.database-platform=${JDBC_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}

# Spring Data JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable H2 Console frame security to allow easy console access if needed
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
